version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: challenges_db
    networks:
      - nestjs
  test-db:
    image: postgres
    ports:
      - 5435:5435
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: challenges_db
    networks:
      - nestjs
networks:
  nestjs:
